apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  strategy: { type: Recreate }
  selector: { matchLabels: { app: webapp } }
  template: # <--- This one is correct, it belongs to the Deployment
    metadata:
      labels: { app: webapp }
    spec:
      containers:
      - name: webapp
        image: IMAGE_PLACEHOLDER 
        ports: [{ containerPort: 8080 }]
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/"
